// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

'use client';
import '../libs/i18n';
import './globals.css';
import Footer from '@/components/Footer';
import { usePathname } from 'next/navigation';

export default function RootLayout({ children }: { children: React.ReactNode }) {
  const pathname = usePathname();
  const allowedRoutes = ['/login', '/register', '/success', '/welcome'];
  const isAllowedRoute = allowedRoutes.includes(pathname);

  return (
    <html lang="en">
      <body>
        {children}
        {!isAllowedRoute && <Footer />}
      </body>
    </html>
  );
}

// "use client";

// import "./globals.css";
// import { useEffect } from "react";

// export default function RootLayout({
//   children,
// }: {
//   children: React.ReactNode;
// }) {
//   useEffect(() => {
//     const addScript = document.createElement("script");
//     addScript.src =
//       "//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit";
//     document.body.appendChild(addScript);

//     (window as any).googleTranslateElementInit = () => {
//       new (window as any).google.translate.TranslateElement(
//         { pageLanguage: "en", includedLanguages: "en,fr,pt" },
//         "google_translate_element"
//       );
//     };
//   }, []);

//   return (
//     <html lang="en">
//       <head>
//             <style>{`
//       .goog-te-banner-frame { display: none !important; }
//       body { top: 0px !important; }
//     `}</style>
//       </head>
//       <body>
//         <div id="google_translate_element"></div>
//         {children}
//       </body>
//     </html>
//   );
// }
